# Generated by Django 5.0.7 on 2024-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_apps', '0002_faq_delete_code_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='warehouse_address',
            field=models.CharField(max_length=200),
        ),
    ]
