# Generated by Django 5.0.7 on 2024-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_apps', '0003_code_delete_faq_alter_client_personal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='warehouse_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
