# Generated by Django 5.0.7 on 2024-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_apps', '0004_alter_client_id_alter_client_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
    ]
